// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import { GOOGLE_MODELS } from "./providers/google.models.ts";
import { GOOGLE_VERTEX_MODELS } from "./providers/google-vertex.models.ts";
import { HUGGINGFACE_MODELS } from "./providers/huggingface.models.ts";
import { MINIMAX_MODELS } from "./providers/minimax.models.ts";
import { MINIMAX_CN_MODELS } from "./providers/minimax-cn.models.ts";
import { MISTRAL_MODELS } from "./providers/mistral.models.ts";
import { MOONSHOTAI_MODELS } from "./providers/moonshotai.models.ts";
import { MOONSHOTAI_CN_MODELS } from "./providers/moonshotai-cn.models.ts";
import { NVIDIA_MODELS } from "./providers/nvidia.models.ts";
import { OPENAI_MODELS } from "./providers/openai.models.ts";
import { OPENROUTER_MODELS } from "./providers/openrouter.models.ts";
import { VERCEL_AI_GATEWAY_MODELS } from "./providers/vercel-ai-gateway.models.ts";
import { XIAOMI_MODELS } from "./providers/xiaomi.models.ts";
import { ZAI_MODELS } from "./providers/zai.models.ts";
import { ZAI_CODING_CN_MODELS } from "./providers/zai-coding-cn.models.ts";

export const MODELS: {
		readonly "google": typeof GOOGLE_MODELS;
	readonly "google-vertex": typeof GOOGLE_VERTEX_MODELS;
	readonly "huggingface": typeof HUGGINGFACE_MODELS;
		readonly "minimax": typeof MINIMAX_MODELS;
	readonly "minimax-cn": typeof MINIMAX_CN_MODELS;
	readonly "mistral": typeof MISTRAL_MODELS;
	readonly "moonshotai": typeof MOONSHOTAI_MODELS;
	readonly "moonshotai-cn": typeof MOONSHOTAI_CN_MODELS;
	readonly "nvidia": typeof NVIDIA_MODELS;
	readonly "openai": typeof OPENAI_MODELS;
	readonly "openrouter": typeof OPENROUTER_MODELS;
	readonly "vercel-ai-gateway": typeof VERCEL_AI_GATEWAY_MODELS;
		readonly "xiaomi": typeof XIAOMI_MODELS;
	readonly "zai": typeof ZAI_MODELS;
	readonly "zai-coding-cn": typeof ZAI_CODING_CN_MODELS;
} = {
		"google": GOOGLE_MODELS,
	"google-vertex": GOOGLE_VERTEX_MODELS,
	"huggingface": HUGGINGFACE_MODELS,
		"minimax": MINIMAX_MODELS,
	"minimax-cn": MINIMAX_CN_MODELS,
	"mistral": MISTRAL_MODELS,
	"moonshotai": MOONSHOTAI_MODELS,
	"moonshotai-cn": MOONSHOTAI_CN_MODELS,
	"nvidia": NVIDIA_MODELS,
	"openai": OPENAI_MODELS,
	"openrouter": OPENROUTER_MODELS,
	"vercel-ai-gateway": VERCEL_AI_GATEWAY_MODELS,
		"xiaomi": XIAOMI_MODELS,
	"zai": ZAI_MODELS,
	"zai-coding-cn": ZAI_CODING_CN_MODELS,
};
