// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import { MOONSHOTAI_MODELS } from "./providers/moonshotai.models.ts";
import { NVIDIA_MODELS } from "./providers/nvidia.models.ts";
import { OPENAI_MODELS } from "./providers/openai.models.ts";
import { OPENROUTER_MODELS } from "./providers/openrouter.models.ts";
import { VERCEL_AI_GATEWAY_MODELS } from "./providers/vercel-ai-gateway.models.ts";
import { XIAOMI_MODELS } from "./providers/xiaomi.models.ts";
import { ZAI_MODELS } from "./providers/zai.models.ts";

export const MODELS: {
	readonly "moonshotai": typeof MOONSHOTAI_MODELS;
	readonly "nvidia": typeof NVIDIA_MODELS;
	readonly "openai": typeof OPENAI_MODELS;
	readonly "openrouter": typeof OPENROUTER_MODELS;
	readonly "vercel-ai-gateway": typeof VERCEL_AI_GATEWAY_MODELS;
		readonly "xiaomi": typeof XIAOMI_MODELS;
	readonly "zai": typeof ZAI_MODELS;
} = {
	"moonshotai": MOONSHOTAI_MODELS,
	"nvidia": NVIDIA_MODELS,
	"openai": OPENAI_MODELS,
	"openrouter": OPENROUTER_MODELS,
	"vercel-ai-gateway": VERCEL_AI_GATEWAY_MODELS,
		"xiaomi": XIAOMI_MODELS,
	"zai": ZAI_MODELS,
};
